### PR TITLE
update to google cloud API for google translate

### PR DESCRIPTION
**Pull request by kkpoon**
changed to google cloud API

and google translate become paid service. pay for your own usage.

### CODE REVIEW

**Comment by kkpoon** [comment]
#9

**Comment by callbacknull** [comment]
+1

**Comment by pchaigno** [comment]
@callbacknull #11 fixes the current error ;)

**Comment by callbacknull** [comment]
@pchaigno won't matter if no one actually maintains this library :/

And I've given up trying use any hubot-scripts....

**Pull request closed without merging**
