### PR TITLE
Update google API endpoint and required params

### LINKED ISSUE #3: Script not functioning at all
IRC interface gives no response to a `hubot translate me` command. Direct invocation of the hubot console results in all translation requests returning `undefined!`.

The command shows up in `help`, so I know I at least have the script installed, but I'm not sure what might be messed up. I'm currently working on updating the hubot instance I help run at https://github.com/thomasrussellmurphy/lulu/tree/fix-translate

### PR DESCRIPTION
**Pull request by Sija**
Fixes #3

### CODE REVIEW

**Comment by radnor** [comment]
:+1:

**Comment by Sija** [comment]
@technicalpickles any chances on pulling it in?

**Comment by technicalpickles** [comment]
@Sija did a quick review, and it looks okay. I'll try to review and test more thoroughly as soon as I can.

**Comment by thomasrussellmurphy** [comment]
Brief test in my instance of hubot works.
+1

**Comment by BlueHatbRit** [comment]
Works for me and looks good. +1

**Comment by Sija** [comment]
@technicalpickles ping?

**Comment by technicalpickles** [comment]
Still haven't gotten to it, sorry.

**Comment by Sija** [comment]
@technicalpickles 2 weeks later... i understand you might be a busy man, but c'mon, clicking "Merge" after 4 positive feedbacks is not that time consuming, huh? :)

**Comment by HaroldPutman** [comment]
@technicalpickles please merge, Translate doesn't work at all right now.

**Comment by bkeepers** [comment]
Tested this locally and confirmed everything looks good. I'll get a release out here in a little bit!

```
hubot> hubot translate bueno
hubot> "bueno" is Spanish for "good"
```

**Comment by bkeepers** [comment]
0.2.0 is out.

Update `package.json`…

```
    "hubot-google-translate": "~0.2.0",
```

and run…

```
$ npm update hubot-google-translate
```

**Comment by BlueHatbRit** [comment]
:+1: thanks!

**Pull request merged**
